import type { Metadata, Viewport } from "next";
import { Poppins } from "next/font/google";
import Providers from "./providers";
import "./globals.css";
import Sidebar from "./_ui/global/navigation";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers >
          <div className="flex">

            <Sidebar />

            <main className="bg-background min-h-screen w-full">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
